prSections:
  - title: "Pull Requests"
    filters: "is:open"
  - title: "Needs My Review"
    filters: "is:open review-requested:@me"
  - title: "Involved"
    filters: "is:open involves:@me -author:@me"

issuesSections:
  - title: "My Issues"
    filters: "is:open"
  - title: "Assigned"
    filters: "is:open assignee:@me"
  - title: "Involved"
    filters: "is:open involves:@me -author:@me"

notificationsSections:
  - title: "All"
    filters: ""
  - title: "Created"
    filters: "reason:author"
  - title: "Participating"
    filters: "reason:participating"
  - title: "Mentioned"
    filters: "reason:mention"
  - title: "Review Requested"
    filters: "reason:review-requested"
  - title: "Assigned"
    filters: "reason:assign"
  - title: "Subscribed"
    filters: "reason:subscribed"
  - title: "Team Mentioned"
    filters: "reason:team-mention"

pager:
  diff: less
showAuthorIcons: true
smartFilteringAtLaunch: true

defaults:
  view: prs
  refetchIntervalMinutes: 5
  layout:
    prs:
      repoName:
        grow: true,
        width: 10
        hidden: false
      base:
        hidden: true
  preview:
    open: true
    width: 84
  prsLimit: 20
  issuesLimit: 20
  notificationsLimit: 20

theme:
  ui:
    sectionsShowCount: true
    table:
      compact: false
  colors:
    text:
      primary: "#E2E1ED"
      secondary: "#666CA6"
      inverted: "#242347"
      faint: "#B0B3BF"
      warning: "#E0AF68"
      success: "#3DF294"
    background:
      selected: "#1B1B33"
    border:
      primary: "#383B5B"
      secondary: "#39386B"
      faint: "#2B2B40"

repoPaths:
  TRIQS/*: ~/git/triqs/*
