unset HDF5_ROOT
unset FFTW_ROOT
unset GMP_ROOT
unset TRIQS_ROOT

export LIBRARY_PATH=$OLD_LIBRARY_PATH
export LD_LIBRARY_PATH=$OLD_LD_LIBRARY_PATH
export PYTHONPATH=$OLD_PYTHONPATH
export PATH=$OLD_PATH

unset CC
unset CXX

unset BLA_VENDOR
unset MKL_INTERFACE_LAYER
unset MKL_THREADING_LAYER
unset CFLAGS
unset CXXFLAGS
