# Same as Black.
line-length = 140
indent-width = 4

[lint]
# 2. Avoid enforcing line-length violations (`E501`)
ignore = ["E501"]

[format]
# Like Black, use double quotes for strings.
quote-style = "single"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
